### ISSUE TITLE
Evaulate PN532 RFID/NFC transmitter

### ISSUE THREAD

**Issue by archerindigo** [ubilab-ws21/puzzle-5#14]
Test if the board works well with ESP32

Play around with the library

**Comment by fedy0** [comment]
[Done!](https://github.com/ubilab-ws21/puzzle-5/pull/26)

**Comment by archerindigo** [comment]
The test code partially works on my side.

nfc.getFirmwareVersion() failed to read from my breakout board, causing the sample program to halt.

Nevertheless, by skipping this part the remaining code works and able to read NFC cards' UID.

**Comment by archerindigo** [comment]
Another bug is that if the NFC reader read a 7-byte-UID tag, the read function will fail forever until the reader is reset.

#51 resolved this problem
