### ISSUE TITLE
HoloCubic PCB Layout update

### ISSUE THREAD

**Issue by archerindigo** [ubilab-ws21/puzzle-5#2]
- Finish the PCB layout for HoloCubic
- Prepare to submit for manufacture
- Push all the EDA files to this repository

**Comment by archerindigo** [comment]
Main board:
https://oshwlab.com/fedy0/game2048

Extension board:
https://oshwlab.com/fedy0/holocube-daughterboard

**Comment by fedy0** [comment]
Done!!!
