### ISSUE TITLE
Bluetooth connection between HoloCube and charger box's MCU

### ISSUE THREAD

**Issue by archerindigo** [ubilab-ws21/puzzle-5#29]
Apart from showing the box's password on the HoloCube, we may alsounlock the box directly through Bluetooth.

**Comment by wjb321** [comment]
1. [x] Know the theory of bluetooth and BLE
2. [x] test different application scenarios of BLE 
3. [ ] holocubic as a client and charger box's mcu as a server v.v.
4. [ ] BLE further application

**Comment by wjb321** [comment]
there are two types of bluetooth: bluetooth and BLE, because I used iPhone and Mac, so bluetooth normally can not support well for iOS. so BLE works well.

- [x] now realized phone as the client and use BLE to control holocubic to play the game
- [x] connect charger box with BLE

**Comment by wjb321** [comment]
now BLE works fine and can control the game. for the commands or information sending to mcu in charger box now change from bluetooth way to mqtt way.  so for the task mentioned above will do after mqtt finished.
